---
- name: Test playbook
  hosts: all
  tasks:
    - name: Install package
      yum:
        name: httpd
        state: present
    
    - name: Start service
      service:
        name: httpd
        state: started
        
    - name: Hard-coded password example (will trigger smell)
      user:
        name: testuser
        password: "plaintext123"
